### ISSUE TITLE
Feature request: URL exception list

### ISSUE THREAD

**Issue by florianbeer** [gggritso/Vimmy.safariextension#9] opened 2016-09-02 18:00 UTC
I'd really love it, if I could exclude some manually inserted URLs from using Vimmy.

For example I am using feedly.com to read RSS feeds and their webapp already has keybindings for `j` and `k` set up, which get overridden by Vimmy.

Thanks for your wonderful plugin!

**Comment by gggritso** [comment] 2016-09-04 20:24
Dupe of #5, right? That said, should the exception list turn off just HJKL navigation, or disable Vimmy completely?

**Comment by florianbeer** [comment] 2016-09-04 20:27
Damn, sorry didn't see #5 

Hmm, good question. At the moment I'd say only tun of h/j/k/l since that's what I guess I use most on the sites that have custom keybindings. Though Gmail, which is mentioned in the other issue, has probably more of them which might conflict with Vimmy (I don't use Gmail's webinterface).

**Comment by florianbeer** [comment] 2016-09-06 09:13
Just to follow up on this: After I have successfully installed the newest Vimmy version from this repo. I am indeed now able to use website-local shortcuts in e.g. Feedly. So I guess this issue can be closed.

**Comment by gggritso** [comment] 2016-09-06 12:36
I don’t have a Feedly account myself, so that’s pretty interesting to me. Does Feedly completely override all Vimmy shortcuts? Do any Vimmy shortcuts override Feedly’s? Is there any overlap at all?

**Comment by gggritso** [comment] 2016-09-25 20:27
Closing since it’s a dupe.

**Closed as completed by gggritso** 2016-09-25 20:27 UTC
