### ISSUE TITLE
User settings for key bindings

### ISSUE THREAD

**Issue by martinbohman** [gggritso/Vimmy.safariextension#42] opened 2017-02-24 13:30 UTC
It would be useful if the user could choose the key bindings.

Things like scroll distance and hint characters would be nice as well.

**Comment by gggritso** [comment] 2017-02-24 20:58
Closing this is a dupe of #21. Please see my comments on that issue, which I still stand by.

**Closed as completed by gggritso** 2017-02-24 20:58 UTC

**Comment by martinbohman** [comment] 2017-02-27 21:32
Ah ok, my bad. I only checked for open issues so I missed that one. Thanks for letting me know!
