### ISSUE TITLE
Add shortcut to open new tab

### ISSUE THREAD

**Issue by kniziol** [gggritso/Vimmy.safariextension#59] opened 2017-07-07 19:46 UTC
`t` shortcut will be nice (like in Vimium for Google Chrome)

**Comment by gggritso** [comment] 2017-07-19 23:09
Duplicate of #50.

**Closed as completed by gggritso** 2017-07-19 23:09 UTC
Labels: enhancement

**Comment by kniziol** [comment] 2017-08-04 13:45
I've found solution:

The _Tab Options_ plugin
http://canisbos.com/taboptions

**Comment by gggritso** [comment] 2017-08-06 15:03
Awesome! I’ve added a note to the wiki.
