### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by icearith** [gggritso/Vimmy.safariextension#76] opened 2018-02-01 02:06 UTC
Refer to [Vimium](https://github.com/philc/vimium)

The smooth scrolling experience of Vimium is awesome, let do something like this.

**Comment by bmichelsen** [comment] 2018-02-01 02:24
It looks like this issue has been raised a few of times before. Specifically, have a look at #28 (and duplicate #64) where @gggritso says that implementing this feature is a lot of work but that he'll gladly accept a PR.

The PR #41 adds a number functionality so you can use `3j` to scroll down three times, and is the reason for why the issue #28 got closed.

Did that help or did I completely miss the question?

**Comment by gggritso** [comment] 2018-02-11 15:23
@bmichelsen thank you for stepping in, that’s exactly right. I’m going to close this issue as a duplicate of #28, but every time this comes up that’s a little kick in the butt for me to reconsider.

**Comment by gggritso** [comment] 2018-02-11 15:23
N.B. Duplicates #28

**Closed as completed by gggritso** 2018-02-11 15:23 UTC
