### ISSUE TITLE
gt and gT don't cycle tabs

### ISSUE THREAD

**Issue by winfr34k** [gggritso/Vimmy.safariextension#7] opened 2016-07-25 08:16 UTC
Just installed the extension on Safari 9.1.2 on El Capitan 10.11.6.

The shortcuts mentioned above don't work and simply do nothing.

**Comment by gggritso** [comment] 2016-07-25 11:00
You have to be focused on the current page. If your cursor is on the menu bar or anywhere else that isn’t the current page, none of the shortcuts work, including those.

**Comment by turboturnip** [comment] 2016-08-30 19:23
Confirmed not working even when focus is right

**Comment by dbmrq** [comment] 2016-08-30 19:26
At first I thought it wasn't working here either, then I realized I didn't have the latest version, and I couldn't update from Safari itself (as in #8). Then I got the latest version here from GitHub and now `gt` and `gT` work.

**Comment by gggritso** [comment] 2016-08-31 01:36
Sorry guys! I must have done something wrong with the update manifest! I will investigate, but in the meantime please install from the release here on GitHub as @dbmrq did. As soon as I get a few more confirmations that the new version fixes this, I’ll close the issue.

**Comment by gggritso** [comment] 2016-09-04 20:25
Since this issue is related to versioning rather than being a bug I’m going to close it. Please update to 0.3.0 by downloading from the Extension Gallery, or following the steps described in #8.

**Closed as completed by gggritso** 2016-09-04 20:25 UTC
